version: '3'

services:
    backend-service:
        build: ./backend
        ports:
            - 5000:5000
        environment:
            - CLIENT_URL=http://localhost:3000

    frontend-service:
        build: ./frontend
        ports:
            - 3000:3000
        environment:
            - REACT_APP_BASE_URL=http://localhost:5000

        links:
            - backend-service
        depends_on:
            - backend-service
